services:
  mysql-master1:
    image: mysql:8.0
    container_name: mysql-master1
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: testdb
      MYSQL_USER: r2d2
      MYSQL_PASSWORD: 123
    ports:
      - "3306:3306"
    volumes:
      - ./master1-data:/var/lib/mysql
      - ./master1-config:/etc/mysql/conf.d
    networks:
      - mysql-replication-net
    command:
      - --server-id=1
      - --log-bin=mysql-bin
      - --binlog-format=ROW
      - --gtid-mode=ON
      - --enforce-gtid-consistency=ON
      - --auto-increment-increment=2
      - --auto-increment-offset=1

  mysql-master2:
    image: mysql:8.0
    container_name: mysql-master2
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: testdb
      MYSQL_USER: r2d2
      MYSQL_PASSWORD: 123
    ports:
      - "3307:3306"
    volumes:
      - ./master2-data:/var/lib/mysql
      - ./master2-config:/etc/mysql/conf.d
    networks:
      - mysql-replication-net
    command:
      - --server-id=2
      - --log-bin=mysql-bin
      - --binlog-format=ROW
      - --gtid-mode=ON
      - --enforce-gtid-consistency=ON
      - --auto-increment-increment=2
      - --auto-increment-offset=2

networks:
  mysql-replication-net:
    driver: bridge